#!/usr/bin/env python3
import parser


def main():
    '''
    With a simple interaction.
    '''
    import sys
    if len(sys.argv) < 2:
        sys.exit(f"Error: expected an .asm file")

    a = sys.argv[1]
    if a == '-h' or a == '--help':
        show_help()
        return

    for a in sys.argv[1:]:
        parser(a)


def show_help():
    print('assemble *.asm to *.hack')


if __name__ == "__main__":
    main()
